
    create table "public"."asset" (
        "amount" numeric(38,2),
        "id" bigint generated by default as identity,
        "ticker" bigint,
        primary key ("id")
    );

    create table "public"."balance" (
        "available" numeric(38,2),
        "id" bigint generated by default as identity,
        primary key ("id")
    );

    create table "public"."candle" (
        "close" numeric(38,2),
        "max" numeric(38,2),
        "min" numeric(38,2),
        "open" numeric(38,2),
        "id" bigint generated by default as identity,
        "interval" bigint,
        "occurred" timestamp(6),
        "ticker" bigint,
        primary key ("id")
    );

    create table "public"."indicator" (
        "id" bigint generated by default as identity,
        "code" varchar(255),
        primary key ("id")
    );

    create table "public"."interval" (
        "id" bigint generated by default as identity,
        "code" varchar(255),
        primary key ("id")
    );

    create table "public"."notification" (
        "id" bigint generated by default as identity,
        "type" bigint,
        "user" bigint,
        "content" varchar(255),
        "event" varchar(255),
        primary key ("id")
    );

    create table "public"."notification_type" (
        "id" bigint generated by default as identity,
        "code" varchar(255),
        primary key ("id")
    );

    create table "public"."provider" (
        "buy_spread" numeric(38,2),
        "enabled" boolean,
        "fixed_commission" numeric(38,2),
        "sell_spread" numeric(38,2),
        "id" bigint generated by default as identity,
        "attrs" varchar(255),
        "code" varchar(255),
        primary key ("id")
    );

    create table "public"."ticker" (
        "autotrade" boolean,
        "enabled" boolean,
        "keep_minimum" numeric(38,2),
        "id" bigint generated by default as identity,
        "ticker" varchar(255),
        primary key ("id")
    );

    create table "public"."token" (
        "revoked" boolean default false,
        "expires_at" timestamp(6),
        "id" bigint generated by default as identity,
        "user" bigint,
        "token" varchar(255),
        primary key ("id")
    );

    create table "public"."trade" (
        "buy_price" numeric(38,2),
        "margin" numeric(38,2),
        "max_price" numeric(38,2),
        "min_price" numeric(38,2),
        "qty" numeric(38,2),
        "sell_price" numeric(38,2),
        "buy_timestamp" timestamp(6),
        "id" bigint generated by default as identity,
        "sell_timestamp" timestamp(6),
        "ticker" bigint,
        primary key ("id")
    );

    create table "public"."transaction" (
        "costs" numeric(38,2),
        "price" numeric(38,2),
        "qty" numeric(38,2),
        "total" numeric(38,2),
        "id" bigint generated by default as identity,
        "occurred" timestamp(6),
        "ticker" bigint,
        primary key ("id")
    );

    create table "public"."trend" (
        "ended" timestamp(6),
        "id" bigint generated by default as identity,
        "indicator" bigint,
        "occurred" timestamp(6),
        "type" bigint,
        "user" bigint,
        primary key ("id")
    );

    create table "public"."trend_type" (
        "id" bigint generated by default as identity,
        "code" varchar(255),
        primary key ("id")
    );

    create table "public"."user" (
        "id" bigint generated by default as identity,
        "email" varchar(100) not null unique,
        "password" varchar(255) not null,
        primary key ("id")
    );

    create table "public"."settings" (
        "id" bigint generated by default as identity,
        "code" varchar(100) not null unique,
        "value" varchar(255),
        primary key ("id")
    );

    alter table if exists "public"."asset" 
       add constraint "FKqsnlcqeme71ti5a7e52dosbbm" 
       foreign key ("ticker") 
       references "public"."ticker";

    alter table if exists "public"."candle" 
       add constraint "FK1jgesffblu0dj7audugixiibe" 
       foreign key ("interval") 
       references "public"."interval";

    alter table if exists "public"."candle" 
       add constraint "FKmc7ur0cpx502d2jujxeo7u0w8" 
       foreign key ("ticker") 
       references "public"."ticker";

    alter table if exists "public"."notification" 
       add constraint "FKy886a4pykgv0ljy7hu944p7m" 
       foreign key ("type") 
       references "public"."notification_type";

    alter table if exists "public"."notification" 
       add constraint "FKp4b5oxxsjiap2xovb9mmd3mu3" 
       foreign key ("user") 
       references "public"."user";

    alter table if exists "public"."token" 
       add constraint "FKegc9g3q3r385xvune5p762u8x" 
       foreign key ("user") 
       references "public"."user";

    alter table if exists "public"."trade" 
       add constraint "FKonfyrlx226ei9gya6i7x6496o" 
       foreign key ("ticker") 
       references "public"."ticker";

    alter table if exists "public"."transaction" 
       add constraint "FKa0jb8kir62pu6xvw1hq7qid0n" 
       foreign key ("ticker") 
       references "public"."ticker";

    alter table if exists "public"."trend" 
       add constraint "FKa3yvpue46ngbaasl4hs5x6ef9" 
       foreign key ("indicator") 
       references "public"."indicator";

    alter table if exists "public"."trend" 
       add constraint "FKgl7ggc9wn31nfav9k4ce2fihu" 
       foreign key ("type") 
       references "public"."trend_type";

    alter table if exists "public"."trend" 
       add constraint "FKlb79idtfffis6070t08ocv3j8" 
       foreign key ("user") 
       references "public"."ticker";
